.PHONY: test
test: RUN=.
test: TAGS=
test:
	go test -c -tags=$(TAGS)
	./xsync.test -test.count=1 -test.v -test.run=$(RUN)

.PHONY: bench
bench: RUN=.
bench:
	go test -c
	./xsync.test -test.count=1 -test.v -test.run=none -test.bench=$(RUN)

.PHONY:
clean:
	find . -name "*_gen.go" -delete

.PHONY: generics
generics: WARNING = Code generated by running "make generics". DO NOT EDIT.
generics:
	for type in "*wg" "task"; do \
		name=$$(echo $$type | tr -d "*") ; \
		cp internal/container/heap_template.go $${name}_heap_gen.go ; \
		sed -i '' -e '1i\'$$'\n''// ${WARNING}' $${name}_heap_gen.go ; \
		sed -i '' -e 's/container/xsync/g' $${name}_heap_gen.go ; \
		sed -i '' -e 's/genericHeapItem/'$${type}'/g' $${name}_heap_gen.go ; \
		sed -i '' -e 's/genericHeap/'$${name}Heap'/g' $${name}_heap_gen.go ; \
	done

